spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  profiles:
    active: service
  datasource:
    url: jdbc:derby:animals_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
server:
  port: 1861
  servlet:
    context-path: /animal

upload:
  use-application-home: true
  path: uploads
  filename:
    unknown: (unknown)
    format: "%1$s-%2$d.%3$s"
    randomizer-limit: 1000000
  timestamp:
    format: yyyyMMddHHmmssSSS
    time-zone: UTC
